server:
  port: 9001
  #port: 8080 # port default

spring:
  application:
    #name: customer_service
    name: customer-service
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27001/microservice_customer_service?authSource=admin
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true