openapi: 3.0.0
info:
  title: API de Gestión de Clientes
  description: API para la gestión de clientes en el bootcamp de microservicios
  version: 1.0.0
paths:
  /api/v1/customers:
    get:
      summary: Obtener todos los clientes
      operationId: getAllCustomers
      responses:
        '200':
          description: Lista de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerDTO'
components:
  schemas:
    CustomerDTO:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        documentNumber:
          type: string